### ISSUE TITLE
Arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by TXPH** [codewyx/rapidcms#1]
# RapidCMS exists arbitrary file upload vulnerability
An arbitrary file upload vulnerability in `/admin/upload.php` allows attackers to getshell
Firstly, we can register an admin account [username:admin / password:admin] .Then enter the website backend and click the article editing button.
<img width="664" alt="截屏2023-07-10 17 16 52" src="https://github.com/OpenRapid/rapidcms/assets/30315062/337ccd4e-8904-4b25-9031-972d8a47976a">
There is an image upload function on this interface. Hackers can upload a normal image first, and then use BurpSuite to intercept it.Then modify the request content: change the file suffix name to PHP and the file content to webshell. Finally, click the send button to upload the malicious file.
![924741d1bf138d1347b6259fd6b408aa](https://github.com/OpenRapid/rapidcms/assets/30315062/3ff1a5c7-aee6-4b8e-9150-48442ebd06e0)
Accessing webshell to getshell `/upload/upload_c1e14b5b6314466a34fc7fc93767a3ca.php`
<img width="1382" alt="截屏2023-07-10 17 25 59" src="https://github.com/OpenRapid/rapidcms/assets/30315062/3117cc46-f64b-4e05-900e-1be78f082c91">
**Fix suggestion:** Set a whitelist for file suffixes uploaded by users

**Comment by codewyx** [comment]
The problem has been resolved. Thank you for your feedback
