### ISSUE TITLE
太多的../

### ISSUE THREAD

**Issue by VBPush** [codewyx/rapidcms#2]
我尝试安装这个CMS但是在安装时发现基本上所有的CSS和JS都全部失效了，导致所有页面均无排版，然后我查看了代码发现基本上所有的PHP文件在寻找层叠样式表时都返回了至少四五层目录结构如../../../../../RXXX/XXX.css，然而下载的目录结构显示只需要返回一层目录即可访问到相关文件，这是开发错误吗？

**Comment by codewyx** [comment]
这个必须安装在根目录，因为一些模板存在子目录，下几个版本会考虑更新，谢谢

**Comment by VBPush** [comment]
> 这个必须安装在根目录，因为一些模板存在子目录，下几个版本会考虑更新，谢谢

**额，抱歉，我安装该CMS时使用的系统为Windows，没考虑到这个只适配了Linux结构**
