### ISSUE TITLE
Administrator password reset vulnerability exists in RapidCMS Dev.1.3.1

### ISSUE THREAD

**Issue by TXPH** [codewyx/rapidcms#5]
RapidCMS Dev.1.3.1 was discovered to contain Administrator password reset vulnerability in `admin/run-movepass.php`.
For more details, see:
[RapidCMS-PasswordReset.pdf](https://github.com/OpenRapid/rapidcms/files/12329073/RapidCMS-PasswordReset.pdf)

**Comment by codewyx** [comment]
This issue has been solved in the latest release.([codewyx](https://github.com/OpenRapid/rapidcms/commits?author=codewyx) committed on Jul 11)
https://github.com/OpenRapid/rapidcms/commit/4dff387283060961c362d50105ff8da8ea40bcbe#diff-fc57d4c69cf5912c6edb5233c6df069a91106ebd481c115faf1ea124478b26d0
